# Generated by Django 4.2.13 on 2024-07-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_rename_full_name_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Cook', 'Cook'), ('Planner', 'Planner'), ('Enthusiast', 'Enthusiast'), ('None', 'None')], default='None', max_length=20, null=True),
        ),
    ]
