# Generated by Django 4.2.13 on 2024-07-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Cook', 'Cook'), ('Planner', 'Planner'), ('Enthusiast', 'Enthusiast'), ('None', 'None')], default='None', max_length=20, null=True),
        ),
    ]
