# Generated by Django 4.2.13 on 2024-06-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(to='recipe.recipe'),
        ),
    ]
